application/auth.py
"""Routes for user authentication."""
from flask import redirect, render_template, flash, Blueprint, request, url_for
from flask_login import login_required, logout_user, current_user, login_user
from flask import current_app as app
from werkzeug.security import generate_password_hash
from .assets import compile_auth_assets
from .forms import LoginForm, SignupForm
from .models import db, User
from .import login_manager


# Blueprint Configuration
auth_bp = Blueprint('auth_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
compile_auth_assets(app)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login_page():
    """User login page."""
    # Bypass Login screen if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))
    login_form = LoginForm(request.form)
    # POST: Create user and redirect them to the app
    if request.method == 'POST':
        if login_form.validate():
            # Get Form Fields
            email = request.form.get('email')
            password = request.form.get('password')
            # Validate Login Attempt
            user = User.query.filter_by(email=email).first()
            if user:
                if user.check_password(password=password):
                    login_user(user)
                    next = request.args.get('next')
                    return redirect(next or url_for('main_bp.dashboard'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login_page'))
    # GET: Serve Log-in page
    return render_template('login.html',
                           form=LoginForm(),
                           title='Log in | Flask-Login Tutorial.',
                           template='login-page',
                           body="Log in with your User account.")


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup_page():
    """User sign-up page."""
    signup_form = SignupForm(request.form)
    # POST: Sign user in
    if request.method == 'POST':
        if signup_form.validate():
            # Get Form Fields
            name = request.form.get('name')
            email = request.form.get('email')
            password = request.form.get('password')
            website = request.form.get('website')
            existing_user = User.query.filter_by(email=email).first()
            if existing_user is None:
                user = User(name=name,
                            email=email,
                            password=generate_password_hash(password, method='sha256'),
                            website=website)
                db.session.add(user)
                db.session.commit()
                login_user(user)
                return redirect(url_for('main_bp.dashboard'))
            flash('A user already exists with that email address.')
            return redirect(url_for('auth_bp.signup_page'))
    # GET: Serve Sign-up page
    return render_template('/signup.html',
                           title='Create an Account | Flask-Login Tutorial.',
                           form=SignupForm(),
                           template='signup-page',
                           body="Sign up for a user account.")


@auth_bp.route("/logout")
@login_required
def logout_page():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login_page'))


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login_page'))

application/routes.py
"""Routes for logged-in application."""
from flask import Blueprint, render_template, session,request, Flask, request, session, url_for, redirect, render_template, g, flash
from flask_login import current_user
from flask import current_app as app
from .assets import compile_auth_assets
from flask_login import login_required
import json
from pathlib import Path


# Blueprint Configuration
main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
compile_auth_assets(app)


@main_bp.route('/', methods=['GET'])
@login_required
def dashboard():
    """Serve logged in Dashboard."""
    session['redis_test'] = 'This is a session variable.'
    return render_template('dashboard.html',
                           title='Flask-Session Tutorial.',
                           template='dashboard-template',
                           current_user=current_user,
                           body="You are now logged in!")


@main_bp.route('/session', methods=['GET'])
@login_required
def session_view():
    """Route which displays session variable value."""
    return render_template('session.html',
                           title='Flask-Session Tutorial.',
                           template='dashboard-template',
                           session_variable=str(session['redis_test']))

@main_bp.route('/calendar',methods=['GET'])
@login_required
def calendar_view():
    return render_template("index.html")

def return_data():
    start_date = request.args.get('start', '')
    end_date = request.args.get('end', '')


    with open("templates/events.json", "r") as input_data:
        return input_data.read()

@main_bp.route('/bus',methods=['GET'])
@login_required
def bus():
    return render_template("bus.html")

@main_bp.route('/map',methods=['GET'])
@login_required
def map():
    return render_template("new_map.html")

@main_bp.route('/yangsan',methods=['GET'])
@login_required
def yangsan():
    return render_template("yangsan.html")

@main_bp.route('/miryang',methods=['GET'])
@login_required
def miryang():
    return render_template("miryang.html")

@main_bp.route("/home", methods=["GET", "POST"])
@login_required
def home():
    if request.method == "POST":
        req = request.form
        name = req["name"].lower()
        data = read_json('users')
        if not name in data:
            return render_template('user not found.html', username=name)
        return redirect("/home/user/{}".format(name))
    return render_template("home.html")

@main_bp.route("/home/user/<name>/")
@login_required
def getUser(name):
    data = read_json('users')
    if not name in data:
        return render_template('user not found.html', username=name)
    list = data[name]['timetable']
    name = name.title()
    cssList = []
    for item in list:
        if item == "":
            cssList.append("")
        else:
            cssList.append("selected")
    return render_template(
    'timetable template.html', list=list, cssList=cssList, username=name)

@main_bp.route("/register", methods=["GET", "POST"])
@login_required
def register():
    if request.method == "POST":
        req = request.form
        name = req["name"].lower()
        data = read_json('users')
        if not name in data:
            data[name] = {}
        data[name]['timetable'] = []
        for item in req:
            if item not in ['name']:
                data[name]['timetable'].append(req[item])
        write_json(data, 'users')
        return redirect("/home/user/{}".format(name))
    return render_template(
    'input form.html',
    nameList=['월요일', '화요일', '수요일', '목요일', '금요일'],
    idList=['monday8am', 'tuesday8am', 'wednesday8am', 'thursday8am', 'friday8am', 'monday9am', 'tuesday9am', 'wednesday9am', 'thursday9am', 'friday9am', 'monday10am', 'tuesday10am', 'wednesday10am', 'thursday10am', 'friday10am', 'monday11am', 'tuesday11am', 'wednesday11am', 'thursday11am', 'friday11am', 'monday12pm', 'tuesday12pm', 'wednesday12pm', 'thursday12pm', 'friday12pm', 'monday1pm', 'tuesday1pm', 'wednesday1pm', 'thursday1pm', 'friday1pm', 'monday2pm', 'tuesday2pm', 'wednesday2pm', 'thursday2pm', 'friday2pm', 'monday3pm', 'tuesday3pm', 'wednesday3pm', 'thursday3pm', 'friday3pm', 'monday4pm', 'tuesday4pm', 'wednesday4pm', 'thursday4pm', 'friday4pm'],
    typeList=['text', 'text', 'text', 'text', 'text'],
    placeholder=[' 월요일 과목을 입력하세요', ' 화요일 과목을 입력하세요', ' 수요일 과목을 입력하세요', ' 목요일 과목을 입력하세요', ' 금요일 과목을 입력하세요']
    )

def get_path():
    cwd = Path(__file__).parents[0]
    cwd = str(cwd)
    return cwd

def read_json(filename):
    cwd = get_path()
    with open(cwd+'/'+filename+'.json', 'r') as file:
        data = json.load(file)
    return data

def write_json(data, filename):
    cwd = get_path()
    with open(cwd+'/'+filename+'.json', 'w') as file:
        json.dump(data, file, indent=4)
        
@login_required
@main_bp.route('/school')
def school():
    return render_template('school.html')

application/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>시간표</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/template.css') }}">
  </head>
  <body>
    {% extends "template.html" %}
    {% block content %}
    <div class="section">
      <h2><span>Timetable search</span></h2>
      <form action="/home" method="POST" color>
        <div class="form-group">
          <label>시간표 이름:</label>
          <input type="text" class="form-control" id="name" name="name" placeholder="시간표 이름을 입력하세요.">
        </div>
        <button type="submit" class="btn btn-primary">검색</button>
      </form>
    </div>
    {% endblock %}
  </body>
</html>

application/templates/index.html
{% extends "layout2.html" %}
{% block body %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset='utf-8' />
    <link href="{{ url_for('static', filename='dist/css/fullcalendar.min.css') }}" rel='stylesheet' />
    <script src="{{ url_for('static', filename='dist/js/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='dist/js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='dist/js/fullcalendar.min.js') }}"></script>
        <script>
            $(document).ready(function () {
                /* initialize the calendar
             -----------------------------------------------------------------*/
                //Date for the calendar events (dummy data)
                var date = new Date();
                var d = date.getDate(),
                    m = date.getMonth(),
                    y = date.getFullYear();
                $('#calendar').fullCalendar({
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,agendaWeek,agendaDay'
                    },
                    editable: true,
                    eventLimit: false, // allow "more" link when too many events
                    events: [
                        {
                            title: 'All Day Event All Day Event All Day Event', 
                            start: new Date(y, m, 1),
                            backgroundColor: "#f56954", //red
                            borderColor: "#f56954" //red                        
                        },
                        {
                            title: 'Long Event',
                            start: new Date(y, m, d - 5),
                            end: new Date(y, m, d - 2),
                            backgroundColor: "#f39c12", //yellow
                            borderColor: "#f39c12" //yellow
                        },
                        {
                            "title": "Repeating Event",
                            start: new Date(y, m, d - 10),
                            end: new Date(y, m, d - 8),
                            backgroundColor: "#00c0ef", //yellow
                            borderColor: "#00c0ef" //yellow
                        },
                        {
                            title: 'Meeting',
                            start: new Date(y, m, d, 10, 30),
                            allDay: false,
                            backgroundColor: "#0073b7", //Blue
                            borderColor: "#0073b7" //Blue
                        },
                        {
                            title: 'Meeting1',
                            start: new Date(y, m, 8, 10, 30),
                            allDay: false,
                            backgroundColor: "#2980b9", //Blue
                            borderColor: "#2980b9" //Blue
                        },
                        {
                            title: 'Meeting2',
                            start: new Date(y, m, 8, 14, 30),
                            allDay: false,
                            backgroundColor: "#27ae60", //Blue
                            borderColor: "#27ae60" //Blue
                        },
                        {
                            "title": "Happy Hour",
                            start: new Date(y, m, 12, 12, 0),
                            end: new Date(y, m, 12, 14, 0),
                            allDay: false,
                            backgroundColor: "#3c8dbc", //Info (aqua)
                            borderColor: "#3c8dbc" //Info (aqua)
                        },
                        {
                            title: 'Lunch',
                            start: new Date(y, m, d, 12, 0),
                            end: new Date(y, m, d, 14, 0),
                            allDay: false,
                            backgroundColor: "#00c0ef", //Info (aqua)
                            borderColor: "#00c0ef" //Info (aqua)
                        },
                        {
                            title: 'Birthday Party',
                            start: new Date(y, m, d + 1, 19, 0),
                            end: new Date(y, m, d + 1, 22, 30),
                            allDay: false,
                            backgroundColor: "#00a65a", //Success (green)
                            borderColor: "#00a65a" //Success (green)
                        },
                        {
                            title: 'Click for Google',
                            start: new Date(y, m, 28),
                            end: new Date(y, m, 29),
                            backgroundColor: "#3c8dbc", //Primary (light-blue)
                            borderColor: "#3c8dbc" //Primary (light-blue)
                        }
                    ],
                    loading: function (bool) {
                        $('#loading').toggle(bool);
                    },
                    eventMouseover: function (event, element) {                    
                        $('<p class="tooltip" style="background-color:'+event.backgroundColor+'"></p>')
                            .text(event.title)
                            .appendTo('body')
                            .fadeIn('fast');                    
                    },
                    eventMouseout: function (event, element) {                    
                        $('.tooltip').remove();
                    },
                    eventRender: function (event, element) {                    

                        element.mousemove(function(e){
                            var mousex = e.pageX + 10; //Get X coordinates
                            var mousey = e.pageY + 5; //Get Y coordinates
                            $('.tooltip')
                                .css({ top: mousey, left: mousex })
                        })

                    }
                });

            });
        </script>
        <style>
            body {
                margin: 0;
                padding: 0;
                font-family: "Lucida Grande", Helvetica, Arial, Verdana, sans-serif;
                font-size: 14px;
            }

            #script-warning {
                display: none;
                background: #eee;
                border-bottom: 1px solid #ddd;
                padding: 0 10px;
                line-height: 40px;
                text-align: center;
                font-weight: bold;
                font-size: 12px;
                color: red;
            }

            #loading {
                display: none;
                position: absolute;
                top: 10px;
                right: 10px;
            }

            #calendar {
                max-width: 900px;
                margin: 40px auto;
                padding: 0 10px;
            }
            /*Custome Stye Calender*/



            .tooltip {
                width: 145px;
                word-wrap: break-word;
                display:none;
                position:absolute;
                border:1px solid #333;
                /*            background-color:#161616;*/
                border-radius:5px;
                padding:10px;
                color:#fff;
                font-size:12px;
                z-index: 9999;
            }

        </style>
    </head>

    <body>
        <div id='calendar'></div>    
    </body>

</html>
{% endblock %}

application/templates/json.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8' />
    <link href="{{ url_for('static', filename='dist/css/fullcalendar.min.css') }}" rel='stylesheet' />
    <script src="{{ url_for('static', filename='dist/js/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='dist/js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='dist/js/fullcalendar.min.js') }}"></script>
    <script>
        $(document).ready(function() {

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                timeFormat: 'h:mma',               
                eventLimit: true, // allow "more" link when too many events
                events: {
                    url: 'events.json',
                    error: function() {
                        $('#script-warning').show();
                    }
                },
                loading: function(bool) {
                    $('#loading').toggle(bool);
                },
                eventMouseover: function (event, element) {                    
                    $('<p class="tooltip" style="background-color:'+event.backgroundColor+'"></p>')
                        .text(event.title)
                        .appendTo('body')
                        .fadeIn('fast');                    
                },
                eventMouseout: function (event, element) {                    
                    $('.tooltip').remove();
                },
                eventRender: function (event, element) {                     


                    element.mousemove(function(e){
                        var mousex = e.pageX + 10; //Get X coordinates
                        var mousey = e.pageY + 5; //Get Y coordinates
                        $('.tooltip')
                            .css({ top: mousey, left: mousex })
                    })

                }
            });

        });
    </script>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: "Lucida Grande", Helvetica, Arial, Verdana, sans-serif;
            font-size: 14px;
        }
        
        #script-warning {
            display: none;
            background: #eee;
            border-bottom: 1px solid #ddd;
            padding: 0 10px;
            line-height: 40px;
            text-align: center;
            font-weight: bold;
            font-size: 12px;
            color: red;
        }
        
        #loading {
            display: none;
            position: absolute;
            top: 10px;
            right: 10px;
        }
        
        #calendar {
            max-width: 900px;
            margin: 40px auto;
            padding: 0 10px;
        }
        /*Custome Stye Calender*/
        

        


        .tooltip {
            width: 145px;
            word-wrap: break-word;
            display:none;
            position:absolute;
            border:1px solid #333;
/*            background-color:#161616;*/
            border-radius:5px;
            padding:10px;
            color:#fff;
            font-size:12px;
            z-index: 9999;
        }
        
    </style>
</head>

<body>

    <div id='script-warning'>
        <code>events.json</code> error
    </div>

    <div id='loading'>loading...</div>

    <div id='calendar'></div>    

</body>

</html>

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'meta.html' %}
    {% block pagestyles %}{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet">
  </head>
  <body class="{{template}}">
    {% block nav %}{% endblock %}
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <!-- Scripts -->
    {% include 'scripts.html' %}
    {% block additionalscripts %}{% endblock %}
  </body>
</html>

application/templates/layout2.html
<!DOCTYPE html>
<html>
    <head>
    <title>{% block title %}환영합니다.{% endblock %}|PNU 에브리타임</title>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">
    </head>
    <body>
    <div class = "container">
        <h1>PNU 에브리타임</h1>
        {% block nav %}
        <nav style="position:absolute; top:50px; right:70px;">
          <a href="{{ url_for('main_bp.session_view') }}" style="color:white">Session test</a> &nbsp;&nbsp;|&nbsp;&nbsp;
          <a href="{{ url_for('auth_bp.logout_page') }}" style="color:white">로그아웃</a> &nbsp;&nbsp;|&nbsp;&nbsp;
          <a href="{{url_for('main_bp.home')}}" style="color:white">시간표</a> &nbsp;&nbsp;|&nbsp;&nbsp;
          <a href="{{ url_for('main_bp.calendar_view') }}" style="color:white">달력</a> &nbsp;&nbsp;|&nbsp;&nbsp;
          <a href="{{url_for('main_bp.map')}}" style="color:white">캠퍼스 지도</a> &nbsp;&nbsp;|&nbsp;&nbsp;
          <a href="{{url_for('main_bp.bus')}}" style="color:white">순환 버스</a>
        </nav>
        {% endblock %}
        {% with flashes = get_flashed_messages() %}
            {% if flashes %}
                <ul class = flashes>
                    {% for message in flashes %}
                        <li>{{message}}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        <div class = "body">
            {% block body %}{% endblock %}
        </div>
        <div class = "footer">
            DSC 솔루션챌린지 &mdash; 플라스크를 이용한 웹 애플리케이션
        </div>
    </div>
    </body>
</html>

application/templates/miryang.html
{% extends "layout2.html" %}
{% block body %}
<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>지도 생성하기</title>  
        </head>
        <body>
            <iframe src="https://map.naver.com/v5/search/%EB%B6%80%EC%82%B0%EB%8C%80%20%EB%B0%80%EC%96%91%EC%BA%A0%ED%8D%BC%EC%8A%A4?c=14338494.8899888,4225799.6108318,15,0,0,0,dh" style="width:1000px; height:500px">
            </iframe>
        </body>
    </html>
{% endblock %}

application/templates/register.html
{% extends "layout.html" %}
{% block title %}회원 등록{% endblock %}
{% block body %}
    <h2>사용자 등록</h2>
    {% if error %}
        <div class=error><strong></strong>{{error}}</div>
    {% endif %}
        <form action="" method="post">
            <dl>
                <dt>사용자 이름 : </dt>
                <dd><input type="text" name = "username" size=30 value = "{{request.form.username}}"/></dd>
                <dt>E-mail : </dt>
                <dd><input type="text" name = "email" size=30 value = "{{request.form.email}}"/></dd>
                <dt>비밀번호 : </dt>
                <dd><input type="password" name = "password" size=30/></dd>
                <dt>비밀번호 확인 : </dt>
                <dd><input type="password" name = "password2" size=30></dd>
            </dl>
            <div class = actions><input type=submit value = "등록하기" /></div>
        </form>
{% endblock %}

application/templates/school.html
{% extends "template.html" %}
{% block body %}
<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>수강 편람</title>  
        </head>
        <body>
            <iframe src="https://e-onestop.pusan.ac.kr/menu/class/C03/C03001?menuId=2000030301&rMenu=03" style="width:1000px; height:500px">
            </iframe>
        </body>
    </html>
{% endblock %}

application/templates/scripts.html
<script src="{{ url_for('static', filename='dist/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='dist/js/main.min.js') }}"></script>

application/templates/session.html
{% extends "layout.html" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
    <h1>{{body}}</h1>
    {% if current_user.is_authenticated %}
    <p class="session">Here's our session variable: <span class="variable">{{session_variable}}</span></p>
  {% endif %}
{% endblock %}

application/templates/template.html
{% extends "layout2.html" %}
{% block body %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Unserializable Software</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/template.css') }}">
</head>
<body>
   <header>
     <div class="section">
       <h2 class="logo"><span>time_table</span></h2>
       <strong><nav>
         <ul class="menu">
           <li><a href="{{ url_for('main_bp.home') }}">시간표 찾기</a></li>
           <li><a href="{{ url_for('main_bp.register') }}">새 시간표 등록</a></li>
           <li><a href="{{ url_for('main_bp.school') }}">수강 편람 보기</a></li>
         </ul>
       </nav></strong>
     </div>
   </header>
   {% block content %}
   {% endblock %}
</body>
</html>
{% endblock %}

application/templates/timetable template.html
{% extends "template.html" %}
{% block content %}
<div class="section">
    <h1><span>{{ username }}</span></h1>
    <table>
        <tr>
            <th>Day</th>
            <th>Mon</th>
            <th>Tue</th>
            <th>Wed</th>
            <th>Thu</th>
            <th>Fri</th>
        </tr>
        <tr>
            <td>8-9 AM</td>
            <td class="{{ cssList[0] }}">{{ list[0] }}</td>
            <td class="{{ cssList[1] }}">{{ list[1] }}</td>
            <td class="{{ cssList[2] }}">{{ list[2] }}</td>
            <td class="{{ cssList[3] }}">{{ list[3] }}</td>
            <td class="{{ cssList[4] }}">{{ list[4] }}</td>
        </tr>
        <tr>
            <td>9-10 AM</td>
            <td class="{{ cssList[5] }}">{{ list[5] }}</td>
            <td class="{{ cssList[6] }}">{{ list[6] }}</td>
            <td class="{{ cssList[7] }}">{{ list[7] }}</td>
            <td class="{{ cssList[8] }}">{{ list[8] }}</td>
            <td class="{{ cssList[9] }}">{{ list[9] }}</td>
        </tr>
        <tr>
            <td>10-11 AM</td>
            <td class="{{ cssList[10] }}">{{ list[10] }}</td>
            <td class="{{ cssList[11] }}">{{ list[11] }}</td>
            <td class="{{ cssList[12] }}">{{ list[12] }}</td>
            <td class="{{ cssList[13] }}">{{ list[13] }}</td>
            <td class="{{ cssList[14] }}">{{ list[14] }}</td>
        </tr>
        <tr>
            <td>11-12 PM</td>
            <td class="{{ cssList[15] }}">{{ list[15] }}</td>
            <td class="{{ cssList[16] }}">{{ list[16] }}</td>
            <td class="{{ cssList[17] }}">{{ list[17] }}</td>
            <td class="{{ cssList[18] }}">{{ list[18] }}</td>
            <td class="{{ cssList[19] }}">{{ list[19] }}</td>
        </tr>
        <tr>
            <td>12-1 PM</td>
            <td class="{{ cssList[20] }}">{{ list[20] }}</td>
            <td class="{{ cssList[21] }}">{{ list[21] }}</td>
            <td class="{{ cssList[22] }}">{{ list[22] }}</td>
            <td class="{{ cssList[23] }}">{{ list[23] }}</td>
            <td class="{{ cssList[24] }}">{{ list[24] }}</td>
        </tr>
        <tr>
            <td>1-2 PM</td>
            <td class="{{ cssList[25] }}">{{ list[25] }}</td>
            <td class="{{ cssList[26] }}">{{ list[26] }}</td>
            <td class="{{ cssList[27] }}">{{ list[27] }}</td>
            <td class="{{ cssList[28] }}">{{ list[28] }}</td>
            <td class="{{ cssList[29] }}">{{ list[29] }}</td>
        </tr>
        <tr>
            <td>2-3 PM</td>
            <td class="{{ cssList[30] }}">{{ list[30] }}</td>
            <td class="{{ cssList[31] }}">{{ list[31] }}</td>
            <td class="{{ cssList[32] }}">{{ list[32] }}</td>
            <td class="{{ cssList[33] }}">{{ list[33] }}</td>
            <td class="{{ cssList[34] }}">{{ list[34] }}</td>
        </tr>
        <tr>
            <td>3-4 PM</td>
            <td class="{{ cssList[35] }}">{{ list[35] }}</td>
            <td class="{{ cssList[36] }}">{{ list[36] }}</td>
            <td class="{{ cssList[37] }}">{{ list[37] }}</td>
            <td class="{{ cssList[38] }}">{{ list[38] }}</td>
            <td class="{{ cssList[39] }}">{{ list[39] }}</td>
        </tr>
        <tr>
            <td>4-5 PM</td>
            <td class="{{ cssList[40] }}">{{ list[40] }}</td>
            <td class="{{ cssList[41] }}">{{ list[41] }}</td>
            <td class="{{ cssList[42] }}">{{ list[42] }}</td>
            <td class="{{ cssList[43] }}">{{ list[43] }}</td>
            <td class="{{ cssList[44] }}">{{ list[44] }}</td>
        </tr>
    </table>
</div>
{% endblock %}

application/templates/user not found.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Invalid Operation</title>
  </head>
  <body>
    {% extends "template.html" %}
    {% block content %}
    <div class="section">
      <h1> Invalid User: {{ username }}</h1>
      <p> 검색 결과가 없습니다. </p>
    </div>
    {% endblock %}
  </body>
</html>

application/templates/yangsan.html
{% extends "layout2.html" %}
{% block body %}
<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>지도 생성하기</title>  
        </head>
        <body>
            <iframe src="https://map.naver.com/v5/search/%EB%B6%80%EC%82%B0%EB%8C%80%20%EC%96%91%EC%82%B0%EC%BA%A0%ED%8D%BC%EC%8A%A4?c=14360167.1761648,4208068.6089267,15,0,0,0,dh" style="width:1000px; height:500px">
            </iframe>
        </body>
    </html>
{% endblock %}